#!/usr/bin/env python3

# Simple email sender for Nigela test
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_nigela_test():
    print("📧 Sending Nigela test email to Palak...")
    
    # Email configuration
    smtp_server = "smtp.gmail.com"
    port = 587
    sender_email = "rushabh@machinecxraft.org"
    password = "Rus981Mac!"  # Your provided password
    receiver_email = "palakbsanghavi@gmail.com"
    
    # Create enhanced email content
    html_content = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nigela Enhanced Test</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', system-ui, sans-serif; background: #ffffff; margin: 0; padding: 20px; color: #000000;">
    <div style="max-width: 340px; margin: 0 auto;">
        
        <!-- Header -->
        <div style="text-align: center; padding: 40px 20px; border-bottom: 1px solid #000000; margin-bottom: 32px;">
            <h1 style="margin: 0; font-size: 24px; font-weight: 400; letter-spacing: 2px; color: #000000;">NIGELA</h1>
            <p style="margin: 8px 0 0 0; font-size: 14px; color: #666666; font-weight: 300; letter-spacing: 1px;">ENHANCED EMAIL TEST</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #999999; font-weight: 300;">Black & White Design Ready</p>
        </div>

        <!-- Main Content -->
        <div style="border: 1px solid #000000; background: white; margin-bottom: 24px;">
            <div style="background: #000000; color: white; padding: 16px; text-align: center;">
                <h2 style="margin: 0; font-size: 16px; font-weight: 500; letter-spacing: 1px;">SYSTEM READY</h2>
            </div>
            
            <div style="padding: 16px;">
                <p style="margin: 0 0 16px 0; font-size: 14px; color: #333;">Hi Palak! 👋</p>
                <p style="margin: 0 0 16px 0; font-size: 13px; color: #666; line-height: 1.5;">🎉 Amazing! Your enhanced Nigela cooking assistant is ready with the beautiful new black & white design inspired by Maruko Labs!</p>
                
                <div style="background: #f8f8f8; padding: 12px; border: 1px solid #e0e0e0; margin: 16px 0;">
                    <h4 style="margin: 0 0 8px 0; font-size: 12px; font-weight: 600; color: #000; letter-spacing: 0.5px;">✨ NEW FEATURES</h4>
                    <ul style="margin: 0; padding-left: 16px; font-size: 11px; color: #333; line-height: 1.6;">
                        <li style="margin-bottom: 3px;">Clean black & white minimal design</li>
                        <li style="margin-bottom: 3px;">Smart recipe cards (complex dishes only)</li>
                        <li style="margin-bottom: 3px;">Complete nutrition analysis with health scores</li>
                        <li style="margin-bottom: 3px;">Soaking instructions for overnight prep</li>
                        <li style="margin-bottom: 3px;">Special cooking comments & health benefits</li>
                        <li style="margin-bottom: 3px;">Grocery management with Blinkit integration</li>
                    </ul>
                </div>
                
                <div style="background: #000000; color: white; padding: 12px; text-align: center; margin: 16px 0;">
                    <p style="margin: 0; font-size: 12px; letter-spacing: 0.5px; font-weight: 600;">DAILY EMAILS START TOMORROW AT 9 PM</p>
                </div>
                
                <p style="margin: 0; text-align: center; font-style: italic; color: #666; font-size: 13px;">With love from your kitchen,<br>Nigela ⚫⚪✨</p>
            </div>
        </div>
        
        <!-- Footer -->
        <div style="text-align: center; padding: 16px 0; border-top: 1px solid #000000;">
            <p style="margin: 0; font-size: 11px; color: #666; font-weight: 300; letter-spacing: 0.5px;">GENERATED BY NIGELA AI COOKING ASSISTANT</p>
            <p style="margin: 4px 0 0 0; font-size: 9px; color: #999; letter-spacing: 0.5px;">ENHANCED DESIGN • POWERED BY OPENAI</p>
        </div>
    </div>
</body>
</html>"""

    text_content = """NIGELA ENHANCED EMAIL TEST

Hi Palak!

🎉 Your enhanced Nigela AI cooking assistant is ready with the beautiful new black & white design!

✨ NEW FEATURES:
• Clean black & white minimal design
• Smart recipe cards (complex dishes only)
• Complete nutrition analysis with health scores
• Soaking instructions for overnight prep
• Special cooking comments & health benefits
• Grocery management with Blinkit integration

📧 DAILY EMAILS START TOMORROW AT 9 PM

With love from your kitchen,
Nigela ⚫⚪✨

Generated by Nigela AI Cooking Assistant"""

    try:
        # Create message
        message = MIMEMultipart("alternative")
        message["Subject"] = "Nigela Enhanced • Black & White Design Ready! ⚫⚪"
        message["From"] = sender_email
        message["To"] = receiver_email
        
        # Add both versions
        message.attach(MIMEText(text_content, "plain"))
        message.attach(MIMEText(html_content, "html"))
        
        # Send email
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_server, port) as server:
            server.starttls(context=context)
            server.login(sender_email, password)
            text = message.as_string()
            server.sendmail(sender_email, receiver_email, text)
        
        print("🎉 SUCCESS! Test email sent to palakbsanghavi@gmail.com")
        print("📱 Palak should receive the enhanced black & white email shortly")
        print("✅ Enhanced Nigela email system is working!")
        
        return True
        
    except Exception as e:
        print(f"❌ Email sending failed: {e}")
        print("💡 May need Gmail app password for automated sending")
        return False

if __name__ == "__main__":
    send_nigela_test()

